#!/usr/bin/python3
from   time    import time, sleep, localtime, strftime
import socket
import struct
import os
os.system('clear')

IP, UDP_PORT = ['192.168.0.11', 61101]

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind((IP, UDP_PORT))

def datetime() : return strftime("%Y-%m-%d %H:%M:%S :", localtime(time()))
 
print(datetime(), IP, UDP_PORT, 'udp_cmd is running')
while True:
    cmd_1, addr = sock.recvfrom(1024)
    cmd_2       = cmd_1.decode("utf-8") 
    print('\n\n', datetime())
    print(addr[0], addr[1], ':', cmd_2)

    if cmd_2 == 'Active?' : result = 'udp_cmd is Active'
    else                  : result = os.popen(cmd_2).read()
    if len(result) == 0   : result = 'udp_cmd OK' 
    print(result)
    rtn_str = bytes(result, 'ASCII')
    sock.sendto(rtn_str, addr)
